name: Build and Release Binaries

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Build binaries
        run: |
          version=${{ github.event.inputs.version }}
          mkdir -p ./bin
          for OS in "linux" "darwin"; do
            for ARCH in "amd64" "arm64"; do
              GOOS=${OS}
              GOARCH=$ARCH
              go build -o bin-manager-${GOOS}-${GOARCH}-${version}
              mv bin-manager-${GOOS}-${GOARCH}-${version} ./bin/
            done
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bin/*
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}