name: Build and Release Binaries

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: crazy-max/ghaction-xgo@v3
        with:
          go-version: 1.23.4
          targets: 'linux/amd64, darwin/amd64, linux/arm64, darwin/arm64'
          dest: 'bin'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bin/*
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}